name: Update Materialgram Repo

on:
  workflow_run:
    workflows: ["Materialgram RPM Builder"]
    types:
      - completed

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    container:
      image: fedora:41
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y git createrepo curl tar jq gpg rpm-sign

      - name: Clone repo
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-repo.git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Import GPG Key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/private-keys.git ~/private-keys
          gpg --batch --allow-secret-key-import --import ~/private-keys/priv.asc
          curl -o ~/.rpmmacros https://raw.githubusercontent.com/burhancodes/materialgram-builder/refs/heads/main/rpmmacros
          echo "$GPG_PASSPHRASE" > /tmp/gpg-passphrase

      - name: Get Latest RPM, Sign and Update Repository
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir materialgram-builder
          cd materialgram-builder
          latest_rpm=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name | endswith(".rpm")) | .name')
          download_url=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name == "'"$latest_rpm"'") | .browser_download_url')
          curl -L -o "$latest_rpm" "$download_url"
          rm -rf ../materialgram-repo/x86_64/
          mkdir -p ../materialgram-repo/x86_64/
          mv "$latest_rpm" ../materialgram-repo/x86_64/
          cd ../materialgram-repo
          createrepo .
          gpg --export -a "$GPG_KEY_ID" > materialgram-public.key
          rpm --addsign x86_64/*.rpm
          gpg --detach-sign --armor repodata/repomd.xml
          expect "Enter passphrase: "
          send -- "$GPG_PASSPHRASE\r"
          expect eof
          git add .
          git commit -m "Update RPM, repodata, and sign metadata"
          git push
