name: Update Materialgram Repo

on:
  workflow_run:
    workflows: ["Materialgram RPM Builder"]
    types:
      - completed

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    container:
      image: fedora:41
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y git createrepo curl tar jq gpg rpm-sign

      - name: Clone repo
        run: |
          export GPG_TTY=$(tty)
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-repo.git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Get Latest RPM, Setup GPG, Sign and Update Repository
        env:
          GPG_TTY: /dev/tty
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir materialgram-builder
          cd materialgram-builder
          latest_rpm=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name | endswith(".rpm")) | .name')
          download_url=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name == "'"$latest_rpm"'") | .browser_download_url')
          curl -L -o "$latest_rpm" "$download_url"
          rm -rf ../materialgram-repo
          mkdir -p ../materialgram-repo/x86_64
          mv "$latest_rpm" ../materialgram-repo/x86_64/
          cd ../materialgram-repo
          createrepo .
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --trust-model always --import
          echo "%_signature gpg" >> ~/.rpmmacros
          echo "%_gpg_name ${GPG_KEY_ID}" >> ~/.rpmmacros
          echo "%__gpg /usr/bin/gpg" >> ~/.rpmmacros
          echo "%__gpg_sign_cmd %{__gpg} gpg --batch --pinentry-mode loopback --passphrase-fd 0 --detach-sign --armor --no-tty --yes -u %{_gpg_name} -o %{__signature_filename} %{__plaintext_filename}" >> ~/.rpmmacros
          gpg --export -a "$GPG_KEY_ID" > materialgram-public.key
          echo "$GPG_PASSPHRASE" | rpmsign --addsign x86_64/*.rpm
          gpg --batch --yes --pinentry-mode loopback \
              --passphrase "$GPG_PASSPHRASE" \
              --detach-sign --armor \
              --default-key "$GPG_KEY_ID" repodata/repomd.xml
          git add .
          git commit -m "Update RPM, repodata, and sign metadata"
          git push
