name: Update Materialgram Repo

on:
  workflow_run:
    workflows: ["Materialgram RPM Builder"]
    types:
      - completed

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    container:
      image: fedora:41
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y git createrepo curl tar jq gpg rpm-sign gpg-preset-passphrase

      - name: Clone repo
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-repo.git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Set up GPG for signing
        run: |
          mkdir -p ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
        shell: bash
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5

      - name: Get Latest RPM, Sign and Update Repository
        env:
          KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir materialgram-builder
          cd materialgram-builder
          latest_rpm=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name | endswith(".rpm")) | .name')
          download_url=$(curl -s https://api.github.com/repos/burhancodes/materialgram-builder/releases/latest | jq -r '.assets[] | select(.name == "'"$latest_rpm"'") | .browser_download_url')
          curl -L -o "$latest_rpm" "$download_url"
          rm -rf ../materialgram-repo
          mkdir -p ../materialgram-repo/x86_64
          mv "$latest_rpm" ../materialgram-repo/x86_64/
          cd ../materialgram-repo
          createrepo .
          cd ..
          curl -sS https://raw.githubusercontent.com/burhancodes/materialgram-builder/refs/heads/main/sign.sh
          chmod +x ./sign.sh
          ./sign.sh materialgram-repo/x86_64/*.rpm materialgram-repo/repodata/repomd.xml
          cd materialgram-repo
          git add .
          git commit -m "Update RPM, repodata, and sign metadata"
          git push
